# Generated by Django 5.1.4 on 2025-01-20 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0002_typeproduct_product_start_price_and_more'),
        ('hrDepartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type_name', models.CharField(max_length=100, unique=True, verbose_name='Название типа ценника')),
                ('tag_type_description', models.TextField(blank=True, null=True, verbose_name='Описание типа ценника')),
            ],
            options={
                'verbose_name': 'Тип ценника',
                'verbose_name_plural': 'Типы ценников',
            },
        ),
        migrations.CreateModel(
            name='StatusResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100, verbose_name='Название статуса')),
                ('status_description', models.CharField(max_length=1000, verbose_name='Описание статуса')),
            ],
            options={
                'verbose_name': 'Статус ответа',
                'verbose_name_plural': 'Статусы ответов',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=1000, verbose_name='Название акции')),
                ('action_description', models.CharField(max_length=1000, verbose_name='Описание акции')),
                ('action_start_date', models.DateTimeField(verbose_name='Дата начала акции')),
                ('action_end_date', models.DateTimeField(verbose_name='Дата окончания акции')),
                ('percent', models.PositiveIntegerField(null=True, verbose_name='Процент скидки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='HCResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода ответа')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrDepartment.employee', verbose_name='ID сотрудника')),
                ('status_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.statusresponse', verbose_name='ID статуса ответа')),
            ],
            options={
                'verbose_name': 'Ответ ГК',
                'verbose_name_plural': 'Ответы ГК',
                'db_table': 'hc_response',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrDepartment.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Список ценников',
                'verbose_name_plural': 'Списки ценников',
            },
        ),
        migrations.CreateModel(
            name='PriceTagProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Установленная цена')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status_stop_list', models.BooleanField(blank=True, null=True, verbose_name='Статус нахождения в стоп-листе')),
                ('price_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.pricelist', verbose_name='Список ценников')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commodity.product', verbose_name='Продукт')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.warehouse', verbose_name='Склад')),
                ('tag_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricetagtype', verbose_name='Тип ценника')),
            ],
            options={
                'verbose_name': 'Ценник',
                'verbose_name_plural': 'Ценники',
            },
        ),
        migrations.CreateModel(
            name='RequestStopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('num_req_stop_list', models.PositiveIntegerField(editable=False, verbose_name='Номер обращения')),
                ('reason', models.TextField(verbose_name='Причина добавления в стоп-лист')),
                ('price_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricetagproduct', verbose_name='Ценник продукта')),
            ],
            options={
                'verbose_name': 'Запрос в стоп-лист',
                'verbose_name_plural': 'Запросы в стоп-лист',
            },
        ),
        migrations.CreateModel(
            name='HCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('quantity_product', models.PositiveIntegerField(verbose_name='Количество продукта')),
                ('commodity_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrDepartment.employee', verbose_name='Эксперт по товарам')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.hcresponse', verbose_name='Ответ от ГК')),
                ('num_req_stop_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.requeststoplist', verbose_name='Номер в стоп-листе')),
                ('status_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.statusresponse', verbose_name='Статус ответа от ГК')),
            ],
            options={
                'verbose_name': 'Запрос к ГК',
                'verbose_name_plural': 'Запросы к ГК',
            },
        ),
    ]
