# Generated by Django 5.1.4 on 2024-12-26 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('manufacturer_name', models.CharField(max_length=100, verbose_name='Название компании производителя')),
                ('manufacturer_country', models.CharField(max_length=100, verbose_name='Страна производителя')),
                ('manufacturer_code', models.CharField(max_length=50, verbose_name='Код компании изготовителя')),
                ('dimensions', models.CharField(max_length=100, verbose_name='Размеры')),
                ('unit_of_measurement', models.CharField(max_length=50, verbose_name='Единицы измерения')),
                ('shelf_life_days', models.PositiveIntegerField(verbose_name='Технический срок годности (дни)')),
                ('barcode', models.CharField(max_length=50, verbose_name='Штрих-код')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('attribute_value', models.CharField(max_length=200, verbose_name='Значение характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='commodity.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='commodity.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='TransferOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.product', verbose_name='Товар')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='commodity.warehouse', verbose_name='Из склада')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='commodity.warehouse', verbose_name='В склад')),
            ],
            options={
                'verbose_name': 'Перемещение товара',
                'verbose_name_plural': 'Перемещения товаров',
            },
        ),
        migrations.CreateModel(
            name='ReceivingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('expiration_date', models.DateField(verbose_name='Срок годности')),
                ('status', models.CharField(choices=[('accepted', 'Принято'), ('rejected', 'Отклонено')], max_length=50, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Приемка товара',
                'verbose_name_plural': 'Приемки товаров',
            },
        ),
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date', models.DateField(verbose_name='Дата инвентаризации')),
                ('discrepancies', models.TextField(blank=True, null=True, verbose_name='Несоответствия')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
            },
        ),
        migrations.CreateModel(
            name='WriteOffOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('reason', models.CharField(max_length=100, verbose_name='Причина списания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Списание товара',
                'verbose_name_plural': 'Списания товаров',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='commodity.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='commodity.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
