# Generated by Django 5.1.4 on 2025-01-20 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('max_percent_of_markdown', models.IntegerField(verbose_name='Максимальный процент скидки')),
                ('days_of_markdown', models.IntegerField(verbose_name='Количество дней скидки')),
                ('max_percent_of_price_change', models.IntegerField(verbose_name='Максимальный процент изменения цены')),
            ],
            options={
                'verbose_name': 'Тип продукта',
                'verbose_name_plural': 'Типы продуктов',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Начальная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=50, unique=True, verbose_name='Штрих-код'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commodity.typeproduct', verbose_name='Категория товара'),
        ),
    ]
